"""empty message

Revision ID: 0ae7fe4e6dd8
Revises: 
Create Date: 2022-09-14 03:11:55.505552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae7fe4e6dd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_cpatcha_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emial', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=10), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emial')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_cpatcha_model')
    # ### end Alembic commands ###
