"""empty message

Revision ID: 68ee85b25b52
Revises: 8541cc8c1024
Create Date: 2022-09-14 03:38:44.290787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68ee85b25b52'
down_revision = '8541cc8c1024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_captcha', sa.Column('email', sa.String(length=100), nullable=False))
    op.drop_index('emial', table_name='email_captcha')
    op.create_unique_constraint(None, 'email_captcha', ['email'])
    op.drop_column('email_captcha', 'emial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_captcha', sa.Column('emial', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'email_captcha', type_='unique')
    op.create_index('emial', 'email_captcha', ['emial'], unique=False)
    op.drop_column('email_captcha', 'email')
    # ### end Alembic commands ###
